/-! Action function ordinals from oracle info.c forward decls.
GENERATED by scripts/gen_info.py — do not edit by hand. -/

namespace Doom.Playsim.Info

/-- Stable action id: 0 = NULL, then declaration order of `A_*` in info.c. -/
abbrev ActionId := UInt32

def actionNull : ActionId := 0
def action_A_Light0 : ActionId := 1
def action_A_WeaponReady : ActionId := 2
def action_A_Lower : ActionId := 3
def action_A_Raise : ActionId := 4
def action_A_Punch : ActionId := 5
def action_A_ReFire : ActionId := 6
def action_A_FirePistol : ActionId := 7
def action_A_Light1 : ActionId := 8
def action_A_FireShotgun : ActionId := 9
def action_A_Light2 : ActionId := 10
def action_A_FireShotgun2 : ActionId := 11
def action_A_CheckReload : ActionId := 12
def action_A_OpenShotgun2 : ActionId := 13
def action_A_LoadShotgun2 : ActionId := 14
def action_A_CloseShotgun2 : ActionId := 15
def action_A_FireCGun : ActionId := 16
def action_A_GunFlash : ActionId := 17
def action_A_FireMissile : ActionId := 18
def action_A_Saw : ActionId := 19
def action_A_FirePlasma : ActionId := 20
def action_A_BFGsound : ActionId := 21
def action_A_FireBFG : ActionId := 22
def action_A_BFGSpray : ActionId := 23
def action_A_Explode : ActionId := 24
def action_A_Pain : ActionId := 25
def action_A_PlayerScream : ActionId := 26
def action_A_Fall : ActionId := 27
def action_A_XScream : ActionId := 28
def action_A_Look : ActionId := 29
def action_A_Chase : ActionId := 30
def action_A_FaceTarget : ActionId := 31
def action_A_PosAttack : ActionId := 32
def action_A_Scream : ActionId := 33
def action_A_SPosAttack : ActionId := 34
def action_A_VileChase : ActionId := 35
def action_A_VileStart : ActionId := 36
def action_A_VileTarget : ActionId := 37
def action_A_VileAttack : ActionId := 38
def action_A_StartFire : ActionId := 39
def action_A_Fire : ActionId := 40
def action_A_FireCrackle : ActionId := 41
def action_A_Tracer : ActionId := 42
def action_A_SkelWhoosh : ActionId := 43
def action_A_SkelFist : ActionId := 44
def action_A_SkelMissile : ActionId := 45
def action_A_FatRaise : ActionId := 46
def action_A_FatAttack1 : ActionId := 47
def action_A_FatAttack2 : ActionId := 48
def action_A_FatAttack3 : ActionId := 49
def action_A_BossDeath : ActionId := 50
def action_A_CPosAttack : ActionId := 51
def action_A_CPosRefire : ActionId := 52
def action_A_TroopAttack : ActionId := 53
def action_A_SargAttack : ActionId := 54
def action_A_HeadAttack : ActionId := 55
def action_A_BruisAttack : ActionId := 56
def action_A_SkullAttack : ActionId := 57
def action_A_Metal : ActionId := 58
def action_A_SpidRefire : ActionId := 59
def action_A_BabyMetal : ActionId := 60
def action_A_BspiAttack : ActionId := 61
def action_A_Hoof : ActionId := 62
def action_A_CyberAttack : ActionId := 63
def action_A_PainAttack : ActionId := 64
def action_A_PainDie : ActionId := 65
def action_A_KeenDie : ActionId := 66
def action_A_BrainPain : ActionId := 67
def action_A_BrainScream : ActionId := 68
def action_A_BrainDie : ActionId := 69
def action_A_BrainAwake : ActionId := 70
def action_A_BrainSpit : ActionId := 71
def action_A_SpawnSound : ActionId := 72
def action_A_SpawnFly : ActionId := 73
def action_A_BrainExplode : ActionId := 74

def NUM_ACTIONS : Nat := 75

end Doom.Playsim.Info
