#!/usr/bin/env python3
"""Mechanically generate Lean lookup-table modules from the oracle C source.

Parses oracle/chocolate-doom/src/tables.c and src/doom/m_random.c and emits:
  lean/Doom/Playsim/Tables/Finesine.lean    (finesine, 10240 x Int32)
  lean/Doom/Playsim/Tables/Finetangent.lean (finetangent, 4096 x Int32)
  lean/Doom/Playsim/Tables/Tantoangle.lean  (tantoangle, 2049 x UInt32)
  lean/Doom/Playsim/Random/Rndtable.lean    (rndtable, 256 x UInt8)

Also prints FNV-1a64 checksums of each table's little-endian entry bytes
(reference values for the Lean test suite).

Deterministic: rerunning must produce a byte-identical no-op diff.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TABLES_C = ROOT / "oracle" / "chocolate-doom" / "src" / "tables.c"
MRANDOM_C = ROOT / "oracle" / "chocolate-doom" / "src" / "doom" / "m_random.c"
OUT_DIR = ROOT / "lean" / "Doom" / "Playsim"

CHUNK = 1024

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3


def parse_c_array(source: str, decl_regex: str) -> list[int]:
    m = re.search(decl_regex + r"\s*=\s*\{(.*?)\};", source, re.DOTALL)
    if m is None:
        raise SystemExit(f"array not found: {decl_regex}")
    body = m.group(1)
    return [int(tok, 0) for tok in re.findall(r"-?(?:0[xX][0-9a-fA-F]+|\d+)", body)]


def fnv1a64(data: bytes) -> int:
    h = FNV_OFFSET
    for b in data:
        h = ((h ^ b) * FNV_PRIME) & 0xFFFFFFFFFFFFFFFF
    return h


def le_bytes(values: list[int], width: int) -> bytes:
    out = bytearray()    # signed values reduced to two's-complement first
    mask = (1 << (8 * width)) - 1
    for v in values:
        out += (v & mask).to_bytes(width, "little")
    return bytes(out)


def emit_table(name: str, values: list[int], elem_ty: str, signed: bool,
               module_doc: str, namespace: str = "Doom.Playsim.Tables") -> str:
    # Signed tables are emitted as two's-complement UInt32 literals (negative
    # Int32 literals make Lean elaboration pathologically slow) and converted
    # to Int32 once at the concatenation step (bit-cast, value-preserving).
    lit_ty = "UInt32" if elem_ty == "Int32" else elem_ty
    mask = 0xFFFFFFFF if elem_ty in ("Int32", "UInt32") else 0xFF
    lines = [
        f"/-! {module_doc}",
        "GENERATED by scripts/gen_tables.py — do not edit by hand. -/",
        "",
        f"namespace {namespace}",
        "",
    ]
    chunks = [values[i:i + CHUNK] for i in range(0, len(values), CHUNK)]
    for ci, chunk in enumerate(chunks):
        lines.append(f"private def {name}Chunk{ci} : Array {lit_ty} := #[")
        for row_start in range(0, len(chunk), 8):
            row = chunk[row_start:row_start + 8]
            body = ", ".join(str(v & mask) for v in row)
            tail = "," if row_start + 8 < len(chunk) else ""
            lines.append(f"  {body}{tail}")
        lines.append("]")
        lines.append("")
    concat = " ++ ".join(f"{name}Chunk{ci}" for ci in range(len(chunks)))
    if lit_ty != elem_ty:
        concat = f"({concat}).map (fun v => v.to{elem_ty})"
    lines.append(f"/-- {len(values)}-entry table, bit-identical to the oracle C source. -/")
    lines.append(f"def {name} : Array {elem_ty} := {concat}")
    lines.append("")
    lines.append(f"end {namespace}")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def main() -> None:
    tables_src = TABLES_C.read_text()
    mrandom_src = MRANDOM_C.read_text()

    finetangent = parse_c_array(tables_src, r"const\s+fixed_t\s+finetangent\[4096\]")
    finesine = parse_c_array(tables_src, r"const\s+fixed_t\s+finesine\[10240\]")
    tantoangle = parse_c_array(tables_src, r"const\s+angle_t\s+tantoangle\[2049\]")
    rndtable = parse_c_array(mrandom_src, r"static\s+const\s+unsigned\s+char\s+rndtable\[256\]")

    assert len(finetangent) == 4096, len(finetangent)
    assert len(finesine) == 10240, len(finesine)
    assert len(tantoangle) == 2049, len(tantoangle)
    assert len(rndtable) == 256, len(rndtable)

    write_if_changed(
        OUT_DIR / "Tables" / "Finesine.lean",
        emit_table("finesine", finesine, "Int32", True,
                   "finesine LUT from oracle tables.c."))
    write_if_changed(
        OUT_DIR / "Tables" / "Finetangent.lean",
        emit_table("finetangent", finetangent, "Int32", True,
                   "finetangent LUT from oracle tables.c."))
    write_if_changed(
        OUT_DIR / "Tables" / "Tantoangle.lean",
        emit_table("tantoangle", tantoangle, "UInt32", False,
                   "tantoangle LUT from oracle tables.c."))
    write_if_changed(
        OUT_DIR / "Random" / "Rndtable.lean",
        emit_table("rndtable", rndtable, "UInt8", False,
                   "rndtable LUT from oracle doom/m_random.c.",
                   namespace="Doom.Playsim.Random"))

    for name, vals, width in (
        ("finesine", finesine, 4),
        ("finetangent", finetangent, 4),
        ("tantoangle", tantoangle, 4),
        ("rndtable", rndtable, 1),
    ):
        print(f"fnv1a64({name}) = 0x{fnv1a64(le_bytes(vals, width)):016x}")


if __name__ == "__main__":
    main()
